services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: trabalho-bd-postgres:17-pgcron
    container_name: trabalho-bd 
    
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - ./schema/extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql
      - ./schema/tabelas.sql:/docker-entrypoint-initdb.d/01-tabelas.sql
      - ./schema/views.sql:/docker-entrypoint-initdb.d/02-allViews.sql
      - ./schema/funcoes.sql:/docker-entrypoint-initdb.d/03-funcoes.sql
      - ./schema/triggers-schedules.sql:/docker-entrypoint-initdb.d/04-triggers-schedules.sql
      - ./schema/indices.sql:/docker-entrypoint-initdb.d/05-indices.sql

      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
