services:
  db:
    image: postgres:17-alpine
    container_name: trabalho-bd 
    
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./allViews.sql:/docker-entrypoint-initdb.d/02-allViews.sql
      - ./allFunctions.sql:/docker-entrypoint-initdb.d/03-allFunctions.sql
      - ./allIndexes.sql:/docker-entrypoint-initdb.d/04-allIndexes.sql
      
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
